_prefs: 
  mapid: srsjojo.4e8d7947
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -97.7365
  - 30.2746
  - 18
description: ''
format: png24
interactivity_layer: ''
layers: null
maxzoom: 20
minzoom: 16
name: Neon Avast
source: "mapbox:///mapbox.mapbox-streets-v5,srsjojo.00021560"
styles: 
  - style.mss
  - labels.mss
  - road.mss
  - top.mss
template: ''
